config/routes.rb
Rails.application.routes.draw do
  root to:'static#index'
  namespace :api, constraints: ->(req) { req.format == :json } do
    resources :things, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '*page', to: 'static#index', constraints: ->(req) { !req.xhr? && req.format.html? }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/thing.rb
class Thing < ApplicationRecord
end

app/controllers/api/things_controller.rb
class Api::ThingsController < ApplicationController
  def index
    render json: { things: [
      Thing.all.sample
    ] }.to_json
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%#= favicon_link_tag 'favicon.ico' %>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/things/_form.html.erb
<%= form_with(model: thing) do |form| %>
  <% if thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
        <% thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :guid %>
    <%= form.text_field :guid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form', thing: @thing %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @thing.guid %>
</p>

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>